name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # (Opcional) Fuerza la actualización de Astro y Tailwind a las últimas versiones
      - name: Update Astro and Tailwind
        run: |
          npm install --save-dev astro@latest @astrojs/tailwind@latest
          # Reinstala todo con las versiones actualizadas
          npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          cname: lucianandreinegoita.dev/es
